---
abstract: 'multi-language source code analysis toolkit'
author:
  - 'Joenio Marques da Costa <joenio@joenio.me>'
build_requires:
  Archive::Extract: '0'
  File::LibMagic: '0'
  File::Share: '0'
  File::ShareDir: '0'
  File::Slurp: '0'
  Git::Wrapper: '0'
  List::MoreUtils: '0'
  Term::UI: '0'
  Test::BDD::Cucumber: '0.61'
  Test::Class: '0'
  Test::Exception: '0'
  Test::MockModule: '0'
  Test::MockObject: '0'
  Test::Spelling: '0'
configure_requires:
  Alien::Doxyparse: '0.17'
  ExtUtils::MakeMaker: '0'
  File::ShareDir::Install: '0.06'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.025, CPAN::Meta::Converter version 2.150010'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Analizo
requires:
  App::Cmd: '0'
  CHI: '0'
  Class::Accessor: '0'
  Class::Inspector: '0'
  DBD::SQLite: '0'
  DBI: '1.635'
  Digest::SHA: '0'
  Env::Path: '0'
  File::Copy::Recursive: '0'
  File::HomeDir: '0'
  FindBin::libs: '0'
  Graph: '0'
  Graph::Writer::Dot: '0'
  JSON: '0'
  List::Compare: '0'
  Statistics::Descriptive: '0'
  Term::ProgressBar: '0'
  YAML::XS: '0.75'
  ZMQ::FFI: '0'
  local::lib: '0'
resources:
  bugtracker: http://github.com/analizo/Analizo/issues
  repository: git://github.com/analizo/analizo.git
version: 1.25.4
x_generated_by_perl: v5.34.0
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: GPL-3.0-only
